services:
  # gateway_api:
  #   build:
  #     context: ./gateway-api
  #     dockerfile: Dockerfile
  #     args:
  #       APP_NAME: api-gateway
  #   env_file:
  #    - ./.env
  #   ports:
  #     - ${GATEWAY_PORT}:${GATEWAY_PORT}
  #   depends_on:
  #     - rabbitmq
  #     - auth-service
  #     - file-service
  #   restart: unless-stopped 
  # auth-service:
  #   build:
  #     context: ./auth-service
  #     dockerfile: Dockerfile
  #     args:
  #       APP_NAME: auth-service
  #   env_file:
  #     - ./auth-service/.env
  #   depends_on:
  #     - rabbitmq
  #     - redis
  #   restart: unless-stopped
  # # file-service:
  #   build:
  #     context: ./file-service
  #     dockerfile: Dockerfile
  #     args:
  #       - APP_NAME=file-service
  #   env_file:
  #     - ./file-service/.env
  #   depends_on:
  #     - rabbitmq
  #     - minio
  #   restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  minio:
    image:  minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    container_name: 'minio'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # MINIO_DEFAULT_BUCKETS: fileStorage
    restart: 'no'
    command: server /data --console-address ":9001"
    volumes:
      - minio_project_data:/data
  redis:
    container_name: redis_db_project
    image: redis:7.4.1-alpine3.20

    ports:
      - 6379:6379
volumes:
  minio_project_data:
    driver: local
  projectData:
