
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  postgres_db:
    container_name: postgres_db_project
    image: postgres:17.0-alpine3.20
    restart: 'no'
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=postgres
    volumes:
      -  projectData:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    container_name: redis_db_project
    image: redis:7.4.1-alpine3.20
  
    ports:
      - 6379:6379
volumes:
    projectData: